### ISSUE TITLE
Atualização de resultados.

### ISSUE THREAD

**Issue by lucas-af** [tiago-sistema/unittest-cache-addon#10]
Analisar possibilidade de atualizar os resultados.
Um "botão" deixando para o usuário essa tarefa?
Ou automaticamente ao clicar no plugin?

**Comment by tiagogribeiro** [comment]
Acredito que poderia ser atualizando em determinado tempo definido pelo usuário, informando sempre o tempo restante para próxima atualização.

**Comment by lucas-af** [comment]
Resolvido. A atualização é feita sempre que abrir o plugin.
